### ISSUE TITLE
Plugin doesn't work in unsaved, empty buffer

### ISSUE THREAD

**Issue by gglanzani** [Arcath/jekyll-new-post#1]
Using the shortcut or via ⇧⌘P. Even if the folder is set (via the tree for example).

**Comment by Arcath** [comment]
As in it doesn't open? or fails to save the new file?

**Comment by gglanzani** [comment]
It does not open (it's like the shortcut has not been pressed)

**Comment by gglanzani** [comment]
Yep, thanks
