### ISSUE TITLE
Remove this package from https://atom.io/packages?

### ISSUE THREAD

**Issue by ghost** [Arcath/jekyll-new-post#12]
Aloha, 

This atom package is no more compatible with the last stable version of Atom (it's not just a _deprecation_ warning) ; and the “new post” functionality can be found in your `jekyll-atom` package. 

Maybe it could be a good idea to remove this one from the atom packages repository?

**Comment by Arcath** [comment]
Yes it is a good idea, I have un published it now

**Comment by ghost** [comment]
Thanks :^)
