### ISSUE TITLE
No settings in configuration

### ISSUE THREAD

**Issue by zommuter** [Arcath/jekyll-new-post#2]
While b80b078a3ced360468c6a46a9446834140439c39 uses `jekyll-new-post.postsDir`and `jekyll-new-post.fileType` to determine the posts directory and file type, one currently has to enter those values manually into ones `config.cson`.

**Comment by Arcath** [comment]
jekyll-new-post is redundant now, it has been replaced by [Arcath/Jekyll-Atom](https://github.com/Arcath/jekyll-atom).

**Comment by zommuter** [comment]
I see, thanks for the quick reply :+1:
